### ISSUE TITLE
webhook not working

### ISSUE THREAD

**Issue by ybservices23** [Mycroft-Studios/mycroft-jobforms#2]
Hey webhook does not work, i tried everyway possible and it did not work

**Comment by ybservices23** [comment]
example i have done what its asked to put the webhook i created in the log settings, in the main/config part either police or default, i tried police and did not work and tried default and still did not work, am i missing a dependency ?

**Comment by JJPivot** [comment]
What was the resolution to this issue? Looks like I am having the same problem.

I received the notification in game that the form was submitted but does not appear in Discord. Ensured that the webhooks are correct, besides of the webhook. Only edited the config.
